### ISSUE TITLE
Pre-trained weights for RiNALMo-135M?

### ISSUE THREAD

**Issue by pshkrh** [lbcb-sci/RiNALMo#13]
Hello! Are there any plans to release the pre-trained weights for the smaller RiNALMo-135M model and/or any of the other configurations available (nano, micro)?

**Comment by retiro** [comment]
Hi,
yes, we plan to release the pre-trained weights for the smaller models in a couple of weeks.

**Comment by xjtu-xsbsy** [comment]
Hi，
now can we get the the smaller RiNALMo-135M model  from somewhere?

**Comment by xjtu-xsbsy** [comment]
Thank You!!!
