### ISSUE TITLE
cluster

### ISSUE THREAD

**Issue by ylzdmm** [lbcb-sci/RiNALMo#5]
Hello, 
I would like to ask how you use MMSeqs2 to cluster RNA, such as what values ​​are set to parameters such as identity and coverage.
Thanks！

**Comment by retiro** [comment]
Hi,
we collected non-coding RNA sequences from publicly available datasets RNAcentral, nt, Rfam and Ensembl. We removed sequence duplicates with ```seqkit rmdup``` and the resulting unique sequences were clustered with ```mmseqs easy-linclust``` with options ```-{}-min-seq-id 0.7``` and ```-c 0.8```.

I hope this will help.
