### ISSUE TITLE
A small issue in layer_norm

### ISSUE THREAD

**Issue by ZhiyuanChen** [lbcb-sci/RiNALMo#9]
Hey, 

Thank you for your great work, it looks awesome. 

When I tried to reproduce your work, I noticed a tiny issue: 

In [line 122-128 of module](https://github.com/lbcb-sci/RiNALMo/blob/da6572dc22617f95f7c657e79b2ea126dc7cf979/rinalmo/model/modules.py#L122-L128), you used the layer norm output of hidden states as residual path of attention, where in standard transformer implementation, the hidden states before layer norm is used as residual path. 

There shouldn't be a big problem, but if anyone is unable to reproduce the claimed result, this may be the cause.

**Comment by RJPenic** [comment]
Hello, thank you for your kind words!

Placement of layer norm you mentioned is a slight oversight but I would advise against moving the layer norm if you decide to use our pretrained weights as we trained the model with the current implementation so I cannot guarantee how well the weights would perform with the slightly different architecture.

**Comment by ZhiyuanChen** [comment]
Thank you for your clarification. 

Yes, I kept your original implementation for consistency.
